FROM node:20-alpine

RUN apk add --no-cache python3 make g++

WORKDIR /usr/app

COPY package*.json ./

RUN npm install

COPY . ./

ENV NODE_ENV=development

EXPOSE 5173

CMD [ "npm", "run", "dev", "--", "--host", "0.0.0.0" ]