services:
  frontend:
    image: mytaskshub-frontend:1.0
    container_name: mytaskshub-frontend
    environment:
      - VITE_BACKEND_API_URL=${VITE_BACKEND_API_URL:-http://localhost:3000}
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
       - .:/usr/app           
       - /usr/app/node_modules 
    ports:
      - "5173:5173"