FROM node:20-alpine AS builder

WORKDIR /usr/app

COPY package*.json ./

RUN npm install

COPY . .

ENV NODE_ENV=production

RUN npm run build

FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/

COPY --from=builder /usr/app/dist /usr/share/nginx/html

EXPOSE 80